import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Disclaimer — Aira',
};

export default function DisclaimerPage() {
  return (
    <div style={{ minHeight: '100vh', background: 'var(--aira-canvas)', padding: '48px 24px' }}>
      <div style={{ maxWidth: 680, margin: '0 auto' }}>
        <Link href="/" style={{ fontFamily: 'JetBrains Mono, monospace', fontSize: 11, color: 'var(--aira-indigo)', textDecoration: 'none', display: 'inline-flex', alignItems: 'center', gap: 4, marginBottom: 32 }}>
          ← Back to Aira
        </Link>
        <h1 style={{ fontFamily: 'Newsreader, Georgia, serif', fontSize: 40, fontWeight: 400, letterSpacing: '-0.025em', color: 'var(--aira-ink)', marginBottom: 8 }}>
          Disclaimer
        </h1>
        <p style={{ fontFamily: 'JetBrains Mono, monospace', fontSize: 11, color: 'var(--aira-ink-4)', marginBottom: 40 }}>
          Last updated: May 2026
        </p>

        <div style={{
          padding: '20px 24px', background: 'var(--aira-saffron-soft)',
          border: '1px solid rgba(220,139,63,0.4)', borderRadius: 14, marginBottom: 32,
        }}>
          <p style={{ fontSize: 15, color: 'var(--aira-saffron-deep)', lineHeight: 1.7, fontWeight: 500 }}>
            ⚠️ Aira uses AI to generate educational responses. AI can make mistakes. Always verify important answers with your teacher, official NCERT textbooks, or CBSE resources before using them for exam preparation.
          </p>
        </div>

        {[
          { title: 'CBSE Attribution', body: 'All board paper questions and marking schemes referenced in Aira are sourced from official CBSE publications (cbseacademic.nic.in). These materials are the intellectual property of the Central Board of Secondary Education (CBSE), Government of India. They are used here strictly for educational fair use to help students study and revise.' },
          { title: 'AI-Generated Content', body: 'Some solutions and explanations in Aira are generated by AI language models (via OpenRouter). These are marked as "AI-generated solution" where applicable. AI-generated content may contain errors, omissions, or inaccuracies. The quality of AI solutions is generally good but not guaranteed to be perfect or aligned exactly with CBSE\'s expected approach.' },
          { title: 'Not Official CBSE', body: 'Aira is an independent educational tool and is NOT affiliated with, endorsed by, or sponsored by the Central Board of Secondary Education (CBSE) or any government body.' },
          { title: 'Academic Integrity', body: 'Aira is designed to help you understand concepts and practice, not to complete assignments or exams for you. Using AI to complete assessed work may violate your school\'s academic integrity policy.' },
        ].map((section) => (
          <div key={section.title} style={{ marginBottom: 32 }}>
            <h2 style={{ fontFamily: 'Newsreader, Georgia, serif', fontSize: 20, fontWeight: 500, color: 'var(--aira-ink)', marginBottom: 10 }}>{section.title}</h2>
            <p style={{ fontSize: 15, color: 'var(--aira-ink-2)', lineHeight: 1.7 }}>{section.body}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
